In [2]:
import numpy as np

a = np.array([[1,2,3], [4,5,6]], dtype = np.float32)

print(a.ndim, a.shape, a.dtype)

2 (2, 3) float32


In [3]:
a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [20]:
#Ones
b = np.ones((3,2),dtype = np.float32)
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)

In [6]:
#Zeros
c = np.zeros((3,3), dtype = np.float32)
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [8]:
#Arrange 
np.arange(103,108)

array([103, 104, 105, 106, 107])

In [10]:
#Concatenate:
np.concatenate([b,c])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [13]:
#AStype:
print(b.astype(np.float32))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
#np.zeros_like
d = np.zeros_like(b)

In [15]:
d

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [57]:
#np.ones_like:
e = np.ones_like(d)
e
f = np.zeros_like(e)
f

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [21]:
A = np.ones((4,1))
B = np.zeros((4,2))

np.concatenate([B, A], axis = 1)

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [28]:
x = np.random.random((10,2,3))
x.ndim

3

In [29]:
x

array([[[7.43538245e-03, 7.61945472e-01, 7.21236879e-01],
        [3.78587715e-01, 7.25918645e-01, 8.06144637e-01]],

       [[8.14978856e-01, 7.89300130e-01, 7.13228469e-01],
        [2.22512674e-01, 9.47374831e-02, 4.69912581e-01]],

       [[1.86351490e-01, 5.58710494e-01, 6.38998280e-01],
        [4.40770420e-01, 3.36566592e-01, 8.12011704e-01]],

       [[9.93546462e-01, 6.45111744e-02, 3.30003000e-01],
        [8.21839268e-01, 1.84455575e-01, 1.65035413e-01]],

       [[8.45947662e-01, 5.94921542e-01, 5.48071653e-01],
        [2.30327965e-01, 5.23110501e-03, 3.55896676e-01]],

       [[5.89420589e-01, 2.31743153e-01, 9.91948608e-02],
        [4.73064576e-01, 5.12917685e-01, 1.99391676e-01]],

       [[2.71915123e-02, 3.65140472e-02, 2.52320905e-01],
        [9.88259553e-01, 3.59207936e-01, 8.82207851e-01]],

       [[7.21453670e-01, 2.14760553e-01, 4.54538292e-01],
        [5.56140828e-01, 2.64172705e-02, 1.48114915e-01]],

       [[3.50922533e-01, 1.03613135e-01, 8.18641712e-01]

In [41]:
a = np.array([1,2,3,4,5,6])

a = a.reshape(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [39]:
a = a.reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [48]:
a = np.arange(10).reshape(5,2)

In [44]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [45]:
a.T

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [49]:
a.transpose((1,0)) 

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [51]:
np.savez('data.npz', a=a)


In [52]:
data = np.load('data.npz')

In [53]:
a = data['a']

In [55]:
data['a']

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])